#!/bin/sh

echo "✨ Formatting staged files..."

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs bunx prettier --write --ignore-unknown
  echo "$STAGED_FILES" | xargs git add
  echo "✅ Files formatted"
else
  echo "✅ No files to format"
fi

exit 0
